name: Augur Code-Gen Claude Trigger

inputs:
  anthropic_api_key:
    description: "Anthropic API key for Claude Code Agent"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract prompt from trigger
      id: extract_prompt
      shell: bash
      env:
        DISPATCH_PROMPT: ${{ github.event.client_payload.prompt }}
        INPUT_PROMPT: ${{ github.event.inputs.claude_prompt }}
      run: |
        if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
          {
            echo 'prompt<<EOF'
            echo "$DISPATCH_PROMPT"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        else
          {
            echo 'prompt<<EOF'
            echo "$INPUT_PROMPT"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        fi

    - name: Run Claude Code Agent
      id: claude_code
      uses: anthropics/claude-code-base-action@beta
      with:
        prompt: "${{ steps.extract_prompt.outputs.prompt }}"
        allowed_tools: "Bash(git:*),View,GlobTool,GrepTool,BatchTool,Write"
        settings: |
          {
            "permissions": {
              "allow": ["Read", "Write", "Bash", "View", "GlobTool", "GrepTool", "BatchTool"]
            }
          }
        max_turns: "100"
        system_prompt: "You are a senior software engineer. Focus on writing clean, maintainable, and well-documented code. Always follow the project's existing patterns and conventions."
        anthropic_api_key: ${{ inputs.anthropic_api_key }}

    - name: Check for changes
      id: check_changes
      shell: bash
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git status --short
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
    - name: Create Pull Request with Generated Code
      id: create_pr
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "AI-generated code changes by Claude Code"
        title: "[Claude Code] Augur PR Fix"
        body: |
          ## AI-Generated Code Changes
          **Prompt:** ${{ steps.extract_prompt.outputs.prompt }}
          This pull request contains code changes generated by Claude Code AI agent.
          ### Execution Details:
          - **Status:** ${{ steps.claude_code.outputs.conclusion }}
          - **Conversation Turns:** ${{ steps.claude_code.outputs.turn_count }}
          - **Model Used:** Claude 3.5 Sonnet (via Anthropic API)
          - **Tools Used:** Git, View, GlobTool, GrepTool, BatchTool, Write
          ### Changes Made:
          - Code generated based on the provided prompt
          - Automated commit by Claude Code workflow
          - All changes reviewed by AI for code quality and conventions
           
          APPROACH:
            1. First, explore the codebase structure using ls and find commands
            2. Use grep to search for relevant code patterns related to the task
            3. Read the relevant files to understand the existing code
            4. Make targeted changes following the existing patterns
            5. Test your changes and commit with clear messages

          Start by exploring - don't assume anything about the project structure.
          **Generated by:** [Claude Code Base Action](https://github.com/marketplace/actions/claude-code-base-action)
          **Workflow:** ${{ github.workflow }}
          **Run ID:** ${{ github.run_id }}
          ---
          *This PR was automatically created. Please review the changes carefully before merging.*
        branch: augur-code-gen-${{ github.run_id }}
        delete-branch: true
        labels: |
          augur-code-gen
          ai-generated
    - name: Log completion
      shell: bash
      run: |
        echo "✅ Augur Code-Gen executed successfully!"
        if [ "${{ steps.create_pr.outputs.pull-request-number }}" != "" ]; then
          echo "🔗 Pull Request created: ${{ steps.create_pr.outputs.pull-request-url }}"
          echo "📝 PR #${{ steps.create_pr.outputs.pull-request-number }}: ${{ steps.create_pr.outputs.pull-request-operation }}"
        else
          echo "ℹ️ No changes were made by Claude Code"
        fi
