name: Augur Code-Gen Claude Trigger

inputs:
  anthropic_api_key:
    description: "Anthropic API key for Claude Code Agent"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract prompt from trigger
      id: extract_prompt
      shell: bash
      env:
        DISPATCH_PROMPT: ${{ github.event.client_payload.prompt }}
        INPUT_PROMPT: ${{ github.event.inputs.claude_prompt }}
      run: |
        if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
          {
            echo 'prompt<<EOF'
            echo "$DISPATCH_PROMPT"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        else
          {
            echo 'prompt<<EOF'
            echo "$INPUT_PROMPT"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        fi

    - name: Run Claude Code Agent
      id: claude_code
      uses: anthropics/claude-code-base-action@beta
      with:
        prompt: "${{ steps.extract_prompt.outputs.prompt }}"
        allowed_tools: "Bash(*),View,GlobTool,GrepTool,BatchTool,Write"
        settings: |
          {
            "permissions": {
              "allow": ["Read", "Write", "Bash", "View", "GlobTool", "GrepTool", "BatchTool"],
              "auto_approve": true
            }
          }
        max_turns: "100"
        system_prompt: |
          You are a senior software engineer working in an automated CI/CD environment. Focus on writing clean, maintainable, and well-documented code. Always follow the project's existing patterns and conventions.

          IMPORTANT: You have ALL permissions - read, write, execute, modify, create files and directories. 
          You can run ANY command, install packages, modify configurations, and make changes.
          Do NOT ask for permission - proceed directly with ALL operations.
          You are running as the 'runner' user with REQUIRED SYSTEM ACCESS and PRIVILEGES.

          Your task:
          1. Explore the codebase structure using ls, find, and grep commands
          2. Read relevant files to understand the existing code patterns
          3. Make the requested changes following existing conventions
          4. Write/modify files as needed without asking for permission
          5. Test your changes when possible
          6. Commit your changes with clear, descriptive messages
          7. Create a summary file 'pr_summary.md' with:
             - Brief title describing what you accomplished
             - List of files changed and why
             - Any important notes or considerations for reviewers
          8. Clean up any temporary files (like output.txt) before finishing

          Focus on writing clean, maintainable, and well-documented code that follows the project's existing patterns and conventions.

          Work autonomously - you are expected to complete the task without human intervention.
        anthropic_api_key: ${{ inputs.anthropic_api_key }}

    - name: Check for changes
      id: check_changes
      shell: bash
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git status --short
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
    - name: Extract PR Summary
      id: extract_summary
      shell: bash
      run: |
        if [[ -f "pr_summary.md" ]]; then
          # Extract title from first line
          PR_TITLE=$(head -n 1 pr_summary.md | sed 's/^# *//')
          echo "custom_title=🤖 ${PR_TITLE}" >> $GITHUB_OUTPUT
          
          # Use static delimiter for multiline output
          {
            echo "custom_summary<<EOF"
            tail -n +2 pr_summary.md
            echo "EOF"
          } >> $GITHUB_OUTPUT
        else
          echo "custom_title=🤖 AI Code Generation: ${{ steps.extract_prompt.outputs.prompt }}" >> $GITHUB_OUTPUT
          echo "custom_summary=" >> $GITHUB_OUTPUT
        fi

    - name: Clean up output.txt
      shell: bash
      run: rm -f output.txt

    - name: Create Pull Request with Generated Code
      id: create_pr
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "AI-generated code changes by Claude Code"
        title: "${{ steps.extract_summary.outputs.custom_title }}"
        body: |
          ${{ steps.extract_summary.outputs.custom_summary }}

          > 🤖 **This PR was automatically created by Augur with Claude Code Agent.** Please review the changes carefully before merging.
          > [Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        branch: augur-code-gen-${{ github.run_id }}
        delete-branch: true
        labels: |
          augur-code-gen
          ai-generated
    - name: Log completion
      shell: bash
      run: |
        echo "✅ Augur Code-Gen executed successfully!"
        if [ "${{ steps.create_pr.outputs.pull-request-number }}" != "" ]; then
          echo "🔗 Pull Request created: ${{ steps.create_pr.outputs.pull-request-url }}"
          echo "📝 PR #${{ steps.create_pr.outputs.pull-request-number }}: ${{ steps.create_pr.outputs.pull-request-operation }}"
        else
          echo "ℹ️ No changes were made by Claude Code"
        fi
